### ISSUE TITLE
This emulator broke my phone, I highly recommend it

### ISSUE THREAD

**Issue by Fernandosin** [DragoPayras228/Horizon-Emu#1]
Besides the fact that he erased almost all my data, he also stole it

**Comment by DragoPayras228** [comment]
Yeah of course. Many people on the channel use it, and only you caught the
virus, and also got the idea from somewhere that your data was stolen.....
Did you see it in the code?)

пт, 10 мая 2024 г., 02:34 Fernandosin ***@***.***>:

**Comment by Fernandosin** [comment]
A friend told me that 18+ content was sent on my behalf in the Discord channel

**Comment by DragoPayras228** [comment]
> Besides the fact that he erased almost all my data, he also stole it

You know, I can also say a lot of things... I wonder why you were hacked?) The rest have been using the emulator for more than 5 days, and there have been no such complaints.
